In [1]:
# importing the necessary packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
# Reading the dataset
dataset=pd.read_csv("Product_purchase.csv")
print(dataset.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0


In [3]:
print(dataset.describe())

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000


In [4]:
print(dataset.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None


In [5]:
# Slicing the dataset
X=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
print(y)
print()
print(np.shape(X))

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]

(400, 2)


In [6]:
# Splitting the dataset into training set and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=1/3,random_state=0)


In [7]:
print(dataset.shape)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 5)
(266, 2)
(134, 2)
(266,)
(134,)


In [8]:
# standardization -StandardScalar
# normalisation - MinMaxScaler
print(X_train[0:10])
from sklearn.preprocessing import StandardScaler
stdsc=StandardScaler()
X_train_std=stdsc.fit_transform(X_train)
X_test_std=stdsc.transform(X_test)
print(X_train_std[0:10])

[[   46 96000]
 [   28 59000]
 [   39 96000]
 [   28 89000]
 [   41 72000]
 [   45 26000]
 [   33 69000]
 [   20 82000]
 [   31 74000]
 [   42 80000]]
[[ 0.81203707  0.7926083 ]
 [-0.96332069 -0.30625786]
 [ 0.12162016  0.7926083 ]
 [-0.96332069  0.5847147 ]
 [ 0.31888214  0.07983025]
 [ 0.71340608 -1.28632769]
 [-0.47016576 -0.00926701]
 [-1.75236858  0.3768211 ]
 [-0.66742773  0.13922842]
 [ 0.41751312  0.31742293]]


In [9]:
print(X_test[0:10])
print(X_test_std[0:10])

[[    30  87000]
 [    38  50000]
 [    35  75000]
 [    30  79000]
 [    35  50000]
 [    27  20000]
 [    31  15000]
 [    36 144000]
 [    18  68000]
 [    47  43000]]
[[-0.76605872  0.52531653]
 [ 0.02298918 -0.57354963]
 [-0.27290378  0.16892751]
 [-0.76605872  0.28772385]
 [-0.27290378 -0.57354963]
 [-1.06195168 -1.4645222 ]
 [-0.66742773 -1.61301763]
 [-0.1742728   2.21816441]
 [-1.94963056 -0.03896609]
 [ 0.91066806 -0.78144323]]


In [10]:
# create an object of the algorithm / model
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0)

In [11]:
# train the model
clf.fit(X_train_std,y_train)

LogisticRegression(random_state=0)

In [12]:
# predict the model on testing dataset
y_pred=clf.predict(X_test_std)

In [13]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.8731343283582089


In [14]:
# create an object of the algorithm / model
from sklearn.linear_model import LogisticRegression
clf1=LogisticRegression(random_state=0)

In [15]:
# train the model
clf1.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [16]:
y_pred1=clf1.predict(X_test)


In [17]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred1))

Accuracy: 0.8731343283582089


In [18]:
# evaluation metrics
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[79  6]
 [11 38]]


In [19]:
from sklearn.metrics import classification_report
print("Report",classification_report(y_test,y_pred))

Report               precision    recall  f1-score   support

           0       0.88      0.93      0.90        85
           1       0.86      0.78      0.82        49

    accuracy                           0.87       134
   macro avg       0.87      0.85      0.86       134
weighted avg       0.87      0.87      0.87       134

