In [ ]:
import numpy as np
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,13.8,16.8,23.1],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.4,11.7,12.8]
])
print("Crop yield array(tonnes):\n",crop_yields)
print(f"The shape of the array is {crop_yields.shape}")
print(f"The size of array is {crop_yields.size}")
print(f"The dimension of array is {crop_yields.ndim}")
print(f"The datatype of the array is {crop_yields.dtype}")
print(f"Total yield:",np.sum(crop_yields))

Crop yield array(tonnes):
 [[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 13.8 16.8 23.1]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.4 11.7 12.8]]
The shape of the array is (4, 5)
The size of array is 20
The dimension of array is 2
The datatype of the array is float64
Total yield: 281.7


In [ ]:
avg_yield_per_farm=np.mean(crop_yields,axis=1)
print("Average yield per farm:",avg_yield_per_farm)
avg_yield_per_season=np.mean(crop_yields,axis=0)
print("Average yield per season:",avg_yield_per_season)
print("The maximum yield is",np.max(crop_yields))
print("The minimum yield is",np.min(crop_yields))
best_farm=np.argmax(avg_yield_per_farm)
print("The best farm is: Farm",best_farm+1)
worst_farm=np.argmin(avg_yield_per_farm)
print("The worst farm is: Farm",worst_farm+1)
best_season=np.argmax(avg_yield_per_season)
print("The best season is: Season",best_season+1)
worst_season=np.argmin(avg_yield_per_season)
print("The worst season is: Season",worst_season+1)
median_yield_per_farm=np.median(crop_yields,axis=1)
print("Median yield per farm:",median_yield_per_farm)
median_yield_per_season=np.median(crop_yields,axis=0)
print("Median yield per season:",median_yield_per_season)
std_yield_per_farm=np.std(crop_yields,axis=1)
print("Standard deviation of yield per farm:",std_yield_per_farm)
std_yield_per_season=np.std(crop_yields,axis=0)
print("Standard deviation of yield per season:",std_yield_per_season)
var_yield_per_farm=np.var(crop_yields,axis=1)
print("Variance of yield per farm:",var_yield_per_farm)
var_yield_per_season=np.var(crop_yields,axis=0)
print("Variance of yield per season:",var_yield_per_season)

Average yield per farm: [13.76 15.1  15.68 11.8 ]
Average yield per season: [12.275 12.6   14.125 14.45  16.975]
The maximum yield is 23.1
The minimum yield is 10.3
The best farm is: Farm 3
The worst farm is: Farm 4
The best season is: Season 5
The worst season is: Season 1
Median yield per farm: [13.8 13.8 15.5 11.7]
Median yield per season: [11.85 12.35 13.95 14.65 16.  ]
Standard deviation of yield per farm: [0.90465463 4.57340136 0.73047929 0.71274119]
Standard deviation of yield per season: [1.8088325  1.52479507 1.35899779 1.91115149 3.81206965]
Variance of yield per farm: [ 0.8184 20.916   0.5336  0.508 ]
Variance of yield per season: [ 3.271875  2.325     1.846875  3.6525   14.531875]


In [ ]:
exceptional=crop_yields >16
print(exceptional)
print("Exceptional yields > 16 are:")
print(crop_yields[exceptional])


[[False False False False False]
 [False False False  True  True]
 [False False  True False  True]
 [False False False False False]]
Exceptional yields > 16 are:
[16.8 23.1 16.2 16.8]


In [ ]:
categories=np.whe