In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))           #typoe of dataset
print(a.dtype)           #type of datatype of elements
print(a.shape)           #Length of the array along the dimension.Returns as tuple
print(a.size)            #size in terms of number of elements
print(a.itemsize)        #size in bytes
print(a.ndim)            #dimension of the array
print(a.nbytes)          #total size in bytes


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
5
8
1
40


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4]])
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np
arr=np.array([[2.0,1,22],[1.1,3,44.1]])
print(arr)                              #converts into float as it is superior

[[ 2.   1.  22. ]
 [ 1.1  3.  44.1]]


In [ ]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[0])            #accessing element using index
print(arr[1]+arr[0])
print(arr[4]-arr[0])
print(arr[1]*arr[2])
print(arr[3]/arr[1])

1
3
4
6
2.0


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,2])


8


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print(arr)
print(arr[0,1,2])        #first array[0],second row[1],third element[2]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
6


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0:2,2])
print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]
[7 8 9]


In [ ]:
print(arr[0:2,1:4])     #getting a sub matrix from the original matrix

[[2 3 4]
 [7 8 9]]


In [ ]:
print(arr[1,1]+arr[1,2])

15


In [ ]:
print(arr[-3:-1,-4:-1])

[[2 3 4]]


In [ ]:
import numpy as np
ar=np.array([1,2,3,4,5])
x=ar.copy()
ar[0]=42
print(x)
print(ar)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
#resizing
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.shape=(3,2)
print(a)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0,11,12])
arr.shape=(4,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]]


In [ ]:
arr.shape=(2,3,2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]


In [ ]:
arr.shape=(3,2,2)
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9  0]
  [11 12]]]


In [ ]:
arr.shape=(2,2,1,3)
print(arr)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[ 0 11 12]]]]


In [ ]:
import numpy as np
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [ ]:
concatenated_arr1=np.concatenate((arr1,arr2),axis=1)
print(concatenated_arr1)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
concatenated_arr1=np.concatenate((arr1,arr2),axis=0)
print(concatenated_arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
transposed_arr1=arr1.transpose()
print(arr1)
print(transposed_arr1)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
flattened_arr1=arr1.flatten()
print(arr1)
print(flattened_arr1)

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print("Original array")      #Everything is converted inrto float
print(a)
print("Checking for complex number")   #a=i+p format for complex number
print(np.iscomplex(a))
print("Checking for real number")
print(np.isreal(a))
print("Checking for scalar type")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number
[ True False False False False  True]
Checking for real number
[False  True  True  True  True False]
Checking for scalar type
True
False


In [ ]:
ar=np.zeros(5)
print(ar)

[0. 0. 0. 0. 0.]


In [ ]:
ar=np.zeros((2,3))
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ar=np.ones((2,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ar=np.empty((2,2))
print(ar)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.identity(2)
print(arr)

[[1. 0.]
 [0. 1.]]
